<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class AWC_Redirect {
	private $awc_redirect_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'awc_redirect_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'awc_redirect_page_init' ) );
	}

	public function awc_redirect_add_plugin_page() {
		add_options_page(
			'AWC Redirect', // page_title
			'AWC Redirect', // menu_title
			'manage_options', // capability
			'awc-redirect', // menu_slug
			array( $this, 'awc_redirect_create_admin_page' ) // function
		);
	}

	public function awc_redirect_create_admin_page() {
		$this->awc_redirect_options = get_option( 'awc_redirect_option_name' ); ?>

		<div class="wrap">
			<h2>AWC Redirect</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'awc_redirect_option_group' );
					do_settings_sections( 'awc-redirect-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function awc_redirect_page_init() {
		register_setting(
			'awc_redirect_option_group', // option_group
			'awc_redirect_option_name', // option_name
			array( $this, 'awc_redirect_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'awc_redirect_setting_section', // id
			'Settings', // title
			array( $this, 'awc_redirect_section_info' ), // callback
			'awc-redirect-admin' // page
		);

		add_settings_field(
			'custom_post_types_0', // id
			'Custom Post Types', // title
			array( $this, 'custom_post_types_0_callback' ), // callback
			'awc-redirect-admin', // page
			'awc_redirect_setting_section' // section
		);
	}

	public function awc_redirect_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['custom_post_types_0'] ) ) {
			$sanitary_values['custom_post_types_0'] = $input['custom_post_types_0'];
		}

		return $sanitary_values;
	}

	public function awc_redirect_section_info() {
		
	}

	public function custom_post_types_0_callback() {
		?> <select name="awc_redirect_option_name[custom_post_types_0]" id="custom_post_types_0" multiple>
			<?php $selected = (isset( $this->awc_redirect_options['custom_post_types_0'] ) && $this->awc_redirect_options['custom_post_types_0'] === 'one') ? 'selected' : '' ; ?>
			<option value="one" <?php echo $selected; ?>>One</option>
			<?php $selected = (isset( $this->awc_redirect_options['custom_post_types_0'] ) && $this->awc_redirect_options['custom_post_types_0'] === 'two') ? 'selected' : '' ; ?>
			<option value="two" <?php echo $selected; ?>>Two</option>
		</select> <?php
	}

	// get all post types that are archived => true

	// loop through and spit out into <select>. If they are set, mark as selected.

}
if ( is_admin() )
	$awc_redirect = new AWC_Redirect();

/* 
 * Retrieve this value with:
 * $awc_redirect_options = get_option( 'awc_redirect_option_name' ); // Array of All Options
 * $custom_post_types_0 = $awc_redirect_options['custom_post_types_0']; // Custom Post Types
 */
